// ORM model definitions (Prisma/Sequelize style)

module.exports = {
  ERPSyncLog: {
    sync_log_id: { type: String, primaryKey: true },
    tenant_id: { type: String, allowNull: false },
    sync_direction: { type: 'ENUM', values: ['INBOUND', 'OUTBOUND'], allowNull: false },
    entity_type: { type: 'ENUM', values: ['SHIPMENT', 'ORDER', 'STOCK_MOVEMENT', 'INVENTORY', 'LOT_SERIAL', 'SKU', 'LOCATION', 'WAREHOUSE', 'ROLE'], allowNull: false },
    entity_id: { type: String, allowNull: false },
    erp_reference_id: { type: String },
    sync_status: { type: 'ENUM', values: ['SUCCESS', 'FAILURE', 'PENDING'], allowNull: false },
    request_payload: { type: 'JSON' },
    response_payload: { type: 'JSON' },
    error_message: { type: String },
    retry_count: { type: Number, allowNull: false },
    synced_at: { type: Date, allowNull: false }
  },
  Shipment: {
    shipment_id: { type: String, primaryKey: true },
    tenant_id: { type: String, allowNull: false },
    order_id: { type: String, allowNull: false },
    carrier_name: { type: String, allowNull: false },
    carrier_service_code: { type: String, allowNull: false },
    tracking_number: { type: String },
    label_url: { type: String },
    shipment_status: { type: 'ENUM', values: ['PENDING', 'SHIPPED', 'DELIVERED', 'RETURNED'], allowNull: false },
    weight_kg: { type: Number },
    dimensions_cm: { type: 'JSON' },
    estimated_delivery_date: { type: Date },
    shipped_at: { type: Date },
    delivered_at: { type: Date },
    created_at: { type: Date, allowNull: false },
    updated_at: { type: Date, allowNull: false }
  },
  Order: {
    order_id: { type: String, primaryKey: true },
    tenant_id: { type: String, allowNull: false },
    order_type: { type: 'ENUM', values: ['STANDARD', 'EXPRESS', 'BULK'], allowNull: false },
    erp_order_number: { type: String, allowNull: false },
    order_status: { type: 'ENUM', values: ['NEW', 'PROCESSING', 'COMPLETED', 'CANCELLED'], allowNull: false },
    expected_date: { type: Date },
    supplier_or_customer_name: { type: String, allowNull: false },
    shipping_address: { type: 'JSON' },
    carrier_id: { type: String },
    line_items: { type: 'JSON', allowNull: false },
    erp_last_sync_at: { type: Date },
    erp_sync_status: { type: 'ENUM', values: ['SYNCHED', 'NOT_SYNCHED'], allowNull: false },
    created_at: { type: Date, allowNull: false },
    updated_at: { type: Date, allowNull: false }
  },
  StockMovement: {
    movement_id: { type: String, primaryKey: true },
    tenant_id: { type: String, allowNull: false },
    movement_type: { type: 'ENUM', values: ['ADD', 'REMOVE', 'TRANSFER'], allowNull: false },
    sku_id: { type: String, allowNull: false },
    lot_serial_id: { type: String },
    from_location_id: { type: String },
    to_location_id: { type: String },
    quantity: { type: Number, allowNull: false },
    uom: { type: String, allowNull: false },
    reference_type: { type: String },
    reference_id: { type: String },
    performed_by_user_id: { type: String, allowNull: false },
    erp_sync_status: { type: 'ENUM', values: ['SYNCHED', 'NOT_SYNCHED'], allowNull: false },
    notes: { type: String },
    movement_timestamp: { type: Date, allowNull: false }
  },
  Inventory: {
    inventory_id: { type: String, primaryKey: true },
    tenant_id: { type: String, allowNull: false },
    location_id: { type: String, allowNull: false },
    sku_id: { type: String, allowNull: false },
    lot_serial_id: { type: String },
    quantity_on_hand: { type: Number, allowNull: false },
    quantity_reserved: { type: Number, allowNull: false },
    quantity_available: { type: Number, allowNull: false },
    uom: { type: String, allowNull: false },
    last_count_date: { type: Date },
    created_at: { type: Date, allowNull: false },
    updated_at: { type: Date, allowNull: false }
  },
  LotSerial: {
    lot_serial_id: { type: String, primaryKey: true },
    tenant_id: { type: String, allowNull: false },
    sku_id: { type: String, allowNull: false },
    tracking_type: { type: 'ENUM', values: ['LOT', 'SERIAL'], allowNull: false },
    lot_number: { type: String },
    serial_number: { type: String },
    manufacture_date: { type: Date },
    expiry_date: { type: Date },
    receipt_date: { type: Date, allowNull: false },
    supplier_lot_ref: { type: String },
    status: { type: String, allowNull: false },
    country_of_origin: { type: String },
    created_at: { type: Date, allowNull: false },
    updated_at: { type: Date, allowNull: false }
  },
  SKU: {
    sku_id: { type: String, primaryKey: true },
    tenant_id: { type: String, allowNull: false },
    sku_code: { type: String, allowNull: false },
    sku_name: { type: String, allowNull: false },
    description: { type: String },
    base_uom: { type: String, allowNull: false },
    uom_conversions: { type: 'JSON' },
    is_lot_tracked: { type: Boolean, allowNull: false },
    is_serial_tracked: { type: Boolean, allowNull: false },
    is_expiry_tracked: { type: Boolean, allowNull: false },
    shelf_life_days: { type: Number },
    weight_kg: { type: Number },
    dimensions_cm: { type: 'JSON' },
    erp_item_code: { type: String },
    hazmat_class: { type: String },
    is_active: { type: Boolean, allowNull: false },
    created_at: { type: Date, allowNull: false },
    updated_at: { type: Date, allowNull: false }
  },
  Location: {
    location_id: { type: String, primaryKey: true },
    warehouse_id: { type: String, allowNull: false },
    parent_location_id: { type: String },
    location_code: { type: String, allowNull: false },
    location_type: { type: 'ENUM', values: ['STORAGE', 'PICKING', 'RECEIVING', 'SHIPPING'], allowNull: false },
    location_name: { type: String, allowNull: false },
    path: { type: String, allowNull: false },
    max_weight_kg: { type: Number },
    max_volume_m3: { type: Number },
    location_status: { type: 'ENUM', values: ['ACTIVE', 'INACTIVE'], allowNull: false },
    is_pickable: { type: Boolean, allowNull: false },
    is_receivable: { type: Boolean, allowNull: false },
    created_at: { type: Date, allowNull: false },
    updated_at: { type: Date, allowNull: false }
  },
  Warehouse: {
    warehouse_id: { type: String, primaryKey: true },
    tenant_id: { type: String, allowNull: false },
    warehouse_code: { type: String, allowNull: false },
    warehouse_name: { type: String, allowNull: false },
    address_line1: { type: String, allowNull: false },
    address_line2: { type: String },
    city: { type: String, allowNull: false },
    state_province: { type: String, allowNull: false },
    postal_code: { type: String, allowNull: false },
    country_code: { type: String, allowNull: false },
    timezone: { type: String, allowNull: false },
    is_active: { type: Boolean, allowNull: false },
    created_at: { type: Date, allowNull: false },
    updated_at: { type: Date, allowNull: false }
  },
  Role: {
    role_id: { type: String, primaryKey: true },
    tenant_id: { type: String, allowNull: false },
    role_name: { type: String, allowNull: false },
    permissions: { type: 'JSON', allowNull: false },
    description: { type: String },
    is_system_role: { type: Boolean, allowNull: false },
    created_at: { type: Date, allowNull: false },
    updated_at: { type: Date, allowNull: false }
  }
};